language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer # FIXME @travis-ci: https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-243534696
jdk:
  - oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
cache:
  directories:
    - "~/.m2/repository"
branches:
  only:
    - "/^(?i:feature)/.*$/"
    - develop
    - master
after_success:
  - mvn clean test jacoco:report coveralls:report
  - "./.travis/before-deploy.sh"
  - "./.travis/deploy.sh"
env:
  global:
    - secure: EdhvLzEpOKEz2kDSU7CcIZSE3pUjlH8gjFZEFLwC5C9LKpua2krheBkOzCg5a/p2R0ODq8j7zWW97g6XejNlMpkNp1pabfRoCXbcW56EViCoX1Cf8Cd2VhPr/X5k8ArjuSlAQJXOwXs6uqiFzmYSc/7SdMvYLF5sJYoI9mFAQfZS3QjldVhJ8AJ3Ovcs4h+ZYIZ4bxpP1MIEcwm+YqoNdH6mjvYrAkiVUC3AxeobRf80nP3K7/QEq93TFy6Yow73k8zodzwS+zYCuFYLpk5Rh/bxWyzpGLXXhQb+e+gmrEwIwVxph4hlqguClhqyN6e9Rw91keUzQ/x2taU6hsGIRUcutwRALQbqky03+NblZZ4HoDPfV/NZIHUdzStLG0Jdxs3sKglvNsqngUUZdnyRHXHPLM8ZntRZRaJX91aJLh/ZKTNuW4wC+1h2EqutNi7pFMfulm2fX5Sv1OaVtd3aOpuQY5EpcNJUXYeqoQFiHqb4hwD9FjN1YJyyxUNeeSKjoyHFoEKd6L5VKr9JfJnkBZW7A6wG/QLPMEbq8df5FVFRpr/cLJgXG+DIECm+HJ73Mz9BlHJQNwjRe7d2VzAbeaGAqSjJ+BETxdV4fyH/5+cvirMbkQohDk516Ki/lDO6bMC5EAm2zge1vq5EQVWq08gPC/ptBwmwwjyAN/IlByQ=
    - secure: IzKkAgx42i1AgZ3zRQrraSQ8eRdAXsHisSqmVXXNeQFjzoPzaCtslp7V82WUH0bD2waGcx6P5Yr1+yfE/q3xttE0OIApJo3CatMmz26qsqLvf0ie84bJR8piaNtkgZNqT257cQltgbpHYT4Csoa/YEAliSkRb95V6VfUqH5uMh0SB6ay2/rUjaJ5uYfYglC/ax9vg/iFiuAG3+vWwPHk6SAwQa3RUCTTW69pDNnvWiF1hdNiU1QuW5K/wLLV6WHoXxxsDSZNM7SUvQ4fod8jeo4dovcU+WLwnTNpVOjb5BTIcyB5GqU4DSfeJhb7Dg7y40wdjyi/kcFNW3JNxWodG/eZ0gsJ4BMYDl6wyd0Cr5oPcqpDmpjikGNb0F/aAu1y8SoHfh/e3mP07cECctoGE87FPA3SMQAJqxg2XNfcF3zZpLSQtyiCHSxy/b5HVrzFaD1gBw/HB75N2YFuhyy+OiDyzgWd4fcOYlMpwtZ3emvLgLv7ue9IhI3BPnx9i/LHdpZZcfAiGOCsiZn9AbfN1QcjtmLHkeDS6VuG8Jq0N15s1KZntAtQIV/iNGRHpvEj1mfyUY5pGjOsKX4zlmCc39G5GYWBNfnAcZo15UQLka93PLi+vLPqTkftgv3u6XNdNQpHMXi+61/cOWeky89yt9o4k0gpCEVppPRwr/k8k9c=
    - secure: bmEnmBNzZ3weg07kVgGp0q1nr5izCLvvOzKwmrW5lM/98/IMMLwx47DgBvqttyXuHEMX48NS6n53Rb8k1JZltCB8LNiC3KHCttuCQ+SXu93Enf7jS9v2Arq6lJjsxyoGDFjmQu+7a7pIuJ5aUh2rAcuJj/174d/2nj72UiRgYWiiFZBBMj8bP1pWsfe/DnfV13oBDl3fR3VaCNmnUnwtjtzETNCDsErkaHdGG52ET1NZM51IK4uRLU+eLxtjWBHQB7wMor4v6Pevt6398opxsvU/DNaHk6ub7z3UKLJ64Jw0Hf2t3AavBP8HCEl9om/iNzWgyxLpbtGBYCnJA1qE8TAysMolHjzCP85mNhKboxR/v20e6CxkDYWFbU9lpZl9QWMAd5U3lVq7Gnlc/BG2N0evhy6cLpsyJNncA6LWguxUbwokyxO9NA2vW/CePfFf8YRoEPGLHnDFMHjViQzbrd3Q8mjXap07ccHn2eGElLdPBKv5wlM7ver3h0jC6u60bYA512SkR8wF7J+uhBfXqo9AUaADDriIavXKWdTjOCVN9Tn/HpywtiK6U9xIXmzkWuXBW+a27sGbKW5O3Ud9CDur8o8EAQnYIjNmDjDO2JCJp6ljl5I4z2nFX6wElnxkwV77mihYjvR55ZCe98mGalpG+QFzEe5CUdMdJo6kV2c=
    - secure: XF4+X/6C3Y8b0n989cJs/hjG402HW7onNC0yQ9u2EI2/rtR1u3m9xUyYp/Oi9H6pV2pV9dFpHSOEPqrICslZWYWuha5b+uKr4O7oXDz0+8QnFmeBgOvcMk3JIAQYoObEImK+QFoZi5bvGqUTANEEkcwd6zCmtR0FogM7tU7jRXmL4f55262gAg0ZwsrrrHJaexgq4pB3qkjhDrpbiCxGEMNrgp66Clt8mn6YGKIJ0reNCRpWuNE+e611GVNc4GLL6Rt3xgLU0hLjVgQYWp27HZeA66xJsXa/VDLb/jjOk1CFjL/3QJDruv/SF6QGtR+Y/4iiimGsBww1A6tconS5U095Y9fr15yoZGHlSazyhFaYLSdMeZ69mbPuLZSc16JgGJKmvqNcPG2W92a/fwioUV2H/jpwl0FdgusbDQZNx/rBCbNI2KMk/HyPLfDkxrN8EEz/i1Z1mZY691hfxcPJ9m/VWpgtDDpcpLaSW3AWmK1SzZW1jOJjeUYFhmidd5fYJKmeBLP3kalfjjgAiHeu1K0R69wARD8/D2MBtDtmjEizqA5NADiCDZghUS9j0uxXrg+sdUOL5HgMWt3DY3KXn/sQBc3ksDXAhJL4+4L/JKCe0VJAZd1Zpk14Hji0tam/LnAQhu8spcXvTVViDtJbOSqignqq3DwSEJl5IzWgzxc=
notifications:
  email:
    - wasabi.honeybadger@gmail.com
